### ISSUE TITLE
Make endgame materials not tankable

### ISSUE THREAD

**Issue by NotMyWing** [NotMyWing/Omnifactory-Self-Torture-Edition#28]
Next materials should not be tankable:
- [ ] Omnium
- [ ] Crystal Matrix
- [ ] Neutronium (?)

**Comment by ALongStringOfNumbers** [comment]
If you are going this far, you might as well remove the liquid crystal matrix ingot as well

**Comment by NotMyWing** [comment]
![image](https://user-images.githubusercontent.com/22255622/89978143-7b87c080-dc75-11ea-8fc3-812ea4c491e4.png)
