### ISSUE TITLE
Make the Mote of Omnium require Singularities instead of regular items, and make Omnium un-tankable.

### ISSUE THREAD

**Issue by scialt61** [NotMyWing/Omnifactory-Self-Torture-Edition#31]
These changes would make the endgame of Omnifactory more "balanced". This would require the player to set up extensive infrastructure to create singularities, challenging their ability to automate and parallelize their infrastructure. It would also be funny.

**Comment by NotMyWing** [comment]
Singularities have never been a good idea.
