### ISSUE TITLE
Add Solidified Experience to a T4.5 MM mission

### ISSUE THREAD

**Issue by Miisi** [NotMyWing/Omnifactory-Self-Torture-Edition#44]
the only way to obtain solidified experience, which is needed for soul binder recipes, is from killing mobs (whether they be passive, neutral or hostile.) this means that one would have to spam a bunch of powered spawners in order to be able to obtain a decent amount of solidified experience.

**Comment by NotMyWing** [comment]
Not necessary since d981f7ecf446e694c70d193a371f1f5def7f6d2b introduced various new fluid/solidified xp recipes.
