### ISSUE TITLE
Thermal elemental dusts costs

### ISSUE THREAD

**Issue by BigKeanerBigWeaner** [NotMyWing/Omnifactory-Self-Torture-Edition#51]
Looking at the recipes for the various thermal elemental dusts, most of them are fairly cheap and automatable (charcoal dust, snow, and netherack dust) however, blitz dust, unlike the other 3 needs end stone dust which can only be made automatically from luminescence. This recipe was included to hate the making of the end cake in regular omni and was succeeded by a cheaper recipe added by dml for end stone. Without this recipe in the pack it is a lot harder to automate primal mana and requires obscene amounts of resources for production of redstone, glowstone, phosphorous and aluminum. 

My solution is to change the recipe for blitz dust to require something. Other than end stone, such as silicon dioxide, obtainable through sand or cobblestone, as this would balance with the other thermal dust recipes as well as maintaining the difficulty of producing end stone from mass tungsten production and make the t3 mm necessary for making tungsten.

**Comment by NotMyWing** [comment]
Very much reasonable.
