### ISSUE TITLE
Fireclay recipe doesn't consume intended dusts

### ISSUE THREAD

**Issue by Tahkra** [NotMyWing/Omnifactory-Self-Torture-Edition#53]
Expected: Craft one fireclay dust from two brick dust and two clay dust.

Actual: The crafting table only consumes half of the ingredients.

Problem: Crafting tables will only consume one ingredient per slot, regardless of the number required for the recipe. The extra dusts are acting as a catalyst to meet the recipe requirement, but aren't actually consumed.

Solution: Replace the current shapeless fireclay dust recipe with
`<ore:dustClay>, <ore:dustClay>, <ore:dustBrick>, <ore:dustBrick>`
and it achieves the desired outcome.

**Comment by UzziD** [comment]
As a result of the existing recipe, you can dupe the fireclay dust by making a batch, then sending it through a centrifuge and making more with the result.
