### ISSUE TITLE
it shows new horizons isntead of omnicraft

### ISSUE THREAD

**Issue by UhahaUhaha** [NotMyWing/Omnifactory-Self-Torture-Edition#73]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.7.10

**Description:**
it shows gt new horizons instead of omnicraft ETS

**Expected Behavior:**
It should show omnicraft

**Steps To Reproduce:**
play omnicraft

**Crash Log:**

**Screenshots:**

**Comment by NotMyWing** [comment]
???
